### ISSUE TITLE
Link to Ward Map on home screen

### ISSUE THREAD

**Issue by hangal** [tcpd/mycity#2]
![image](https://user-images.githubusercontent.com/1018175/34299282-22bc3c44-e748-11e7-8226-ac7936a05ed7.png)

On the home screen, below Year, provide a link saying "Ward Map" to:

https://www.google.com/maps/d/edit?mid=1rUTFsbG77WHfUmyTDHki803Btog&ll=15.416828430186818%2C75.0198780583496&z=12

**Comment by hangal** [comment]
@hoominchu can you add this quickly?

**Comment by hoominchu** [comment]
Done
